---
- name: Load library files
  when: library_mode == 'load'
  ansible.builtin.include_tasks: load.yml
- name: Dump library files
  when: library_mode == 'dump'
  ansible.builtin.include_tasks: dump.yml
