---
- name: Determine Homebrew ownership variables
  ansible.builtin.set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'
- name: Determine dump file
  ansible.builtin.set_fact:
    crontab_dump_file: "{{ playbook_dir }}/files/crontab"

- name: List existing crontab
  ansible.builtin.command: crontab -l
  failed_when: false
  register: crontab
  changed_when: false
- name: Backup crontab to file
  when: crontab is succeeded
  ansible.builtin.copy:
    content: "{{ crontab.stdout }}"
    dest: "crontab.{{ ansible_date_time.iso8601_basic_short }}.bak"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: '0600'
    force: "yes"
- name: Load crontab
  ansible.builtin.command: "crontab {{ crontab_dump_file }}"
  changed_when: true
