# See homebrew.py plugin in ansible community.general and to homebrew-bundle README
---
- name: "Extract brew name..."
  ansible.builtin.set_fact:
    brew_name: "{{ item | regex_replace('^brew \"(.+)\".*$', '\\1') }}"
  changed_when: false
- name: ".. install brew {{ brew_name }}"
  when: "brew_name not in homebrew_installed_brews.stdout_lines"
  ansible.builtin.shell: "{{ homebrew_brew_bin_path | quote }}/brew bundle --file=- <<< {{ item | quote }}"
