# See homebrew_cask.py plugin in ansible community.general and to homebrew-bundle README
---
- set_fact:
    cask_name: "{{ item | regex_replace('^cask \"(.+)\".*$', '\\1') }}"
  changed_when: false
- name: "Install cask {{ cask_name }}"
  when: "cask_name not in homebrew_installed_casks.stdout_lines"
  shell: |
    {{ homebrew_brew_bin_path | quote }}/brew bundle --file=- << EOF
    {% if homebrew_brewfile_cask_args -%}
    {{ homebrew_brewfile_cask_args }}
    {% endif -%}
    {{ item }}
    EOF
