---
- name: Determine Homebrew ownership variables
  set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'
- name: Determine dump file
  set_fact:
    etchosts_dump_file: "{{ playbook_dir }}/files/hosts"

- name: Dump /etc/hosts to file
  copy:
    content: "{{ lookup('file', '/etc/hosts') }}"
    dest: "{{ etchosts_dump_file }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: '0600'
    force: "yes"
