---
- name: Determine Homebrew ownership variables
  ansible.builtin.set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'
- name: Determine dump file
  ansible.builtin.set_fact:
    etchosts_dump_file: "{{ playbook_dir }}/files/hosts"

- name: Read /etc/hosts
  ansible.builtin.slurp:
    src: "/etc/hosts"
  register: etchosts
- name: Backup /etc/hosts to file
  ansible.builtin.copy:
    content: "{{ etchosts.content }}"
    dest: "etchosts.{{ ansible_date_time.iso8601_basic_short }}.bak"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: '0600'
    force: "yes"
- name: Load /etc/hosts
  ansible.builtin.copy:
    src: "{{ etchosts_dump_file }}"
    dest: "/etc/hosts"
  become: true
