---
- name: Load /etc/hosts
  when: etchosts_mode == 'load'
  ansible.builtin.include_tasks: load.yml
- name: Dump /etc/hosts
  when: etchosts_mode == 'dump'
  ansible.builtin.include_tasks: dump.yml
