---
- name: Determine Homebrew ownership variables
  ansible.builtin.set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'
- name: Determine dump file
  ansible.builtin.set_fact:
    gpg_pub_dump_file: "{{ playbook_dir }}/files/gpg/pubkeys.gpg"
    gpg_priv_dump_file: "{{ playbook_dir }}/files/gpg/privkeys.gpg"

- name: Get pub keys
  ansible.builtin.command: "gpg --export --armor"
  changed_when: true
  register: gpg_pub
- name: Get priv keys
  ansible.builtin.command: "gpg --export-secret-keys --armor"
  changed_when: true
  register: gpg_priv
  failed_when: false
- name: Write pub keys file
  ansible.builtin.copy:
    content: "{{ gpg_pub.stdout }}"
    dest: "{{ gpg_pub_dump_file }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: '0600'
    force: "yes"
- name: Write priv keys file
  ansible.builtin.copy:
    content: "{{ gpg_priv.stdout }}"
    dest: "{{ gpg_priv_dump_file }}"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"
    mode: '0600'
    force: "yes"
