---
- name: Determine Homebrew ownership variables
  ansible.builtin.set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'
- name: Determine dump file
  ansible.builtin.set_fact:
    gpg_pub_dump_file: "{{ playbook_dir }}/files/gpg/pubkeys.gpg"
    gpg_priv_dump_file: "{{ playbook_dir }}/files/gpg/privkeys.gpg"

- name: Import pub keys
  ansible.builtin.command: "gpg --import {{ gpg_pub_dump_file }}"
  changed_when: true

- name: Import priv keys
  ansible.builtin.command: "gpg --import {{ gpg_priv_dump_file }}"
  changed_when: true
  failed_when: false
